name: Tf Security Check
on: [push]

jobs:
  securitychk:
    name: Security Check
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Terraform Sec Scan
      uses: triat/terraform-security-scan@v2.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}